import { Link } from "react-router-dom";
import { FiArrowRight, FiArrowUpRight, FiCode, FiPenTool, FiTrendingUp, FiBookOpen, FiBriefcase, FiActivity, FiDollarSign } from "react-icons/fi";
import { useUser } from "../Authentication/useUser";
const categories = [["Development", "development", FiCode, "Web, mobile, games & data"], ["Design", "design", FiPenTool, "Visual design & digital experiences"], ["Marketing", "marketing", FiTrendingUp, "Brands, audiences & growth"], ["Academics", "academics", FiBookOpen, "Research, medicine & writing"], ["Business", "business", FiBriefcase, "Ideas, leadership & strategy"], ["Finance", "finance", FiDollarSign, "Money, markets & accounting"], ["Health & fitness", "fitness", FiActivity, "Movement, nutrition & wellbeing"]];
export default function Home() {
  const { user } = useUser();
  const name = (user?.user_metadata?.fullname || user?.user_metadata?.full_name || "Learner").split(" ")[0];
  return <div className="discover-page"><header className="page-heading"><span className="eyebrow">YOUR LEARNING, YOUR WAY</span><h1>Good to see you, {name}.</h1><p>Follow your curiosity. Find something you’ll love learning.</p></header><section className="discover-banner"><div><span className="eyebrow">ONE STEP CLOSER</span><h2>Your next chapter<br /><em>is waiting.</em></h2><p>New ideas, practical skills, and a little room to grow.</p><Link className="btn btn-primary" to="/mylearning">Go to my learning <FiArrowRight /></Link></div><div className="banner-art" aria-hidden="true"><span>learn.</span><span>try.</span><span>grow.<FiArrowUpRight /></span></div></section><div className="section-heading"><h2>Explore your possibilities</h2><span>7 subjects. Endless directions.</span></div><div className="discovery-grid">{categories.map(([title, slug, Icon, description], index) => <Link className="discovery-card" key={slug} to={`/${slug}/${slug}-hero`}><div className="path-card-top"><span className={`category-icon tone-${index % 4}`}><Icon /></span><FiArrowUpRight /></div><h3>{title}</h3><p>{description}</p><span className="text-link">Explore subject <FiArrowRight /></span></Link>)}</div></div>;
}
