import { Link } from "react-router-dom";
import { FiArrowRight, FiArrowUpRight, FiCode, FiPenTool, FiTrendingUp, FiBookOpen, FiBriefcase, FiActivity, FiDollarSign, FiCheck, FiPlay } from "react-icons/fi";
import Brand from "../../Ui/Brand";
const topics = [["Development", FiCode, "Build something that matters."], ["Design", FiPenTool, "Turn your ideas into experiences."], ["Marketing", FiTrendingUp, "Connect with the right people."], ["Academics", FiBookOpen, "Take your knowledge further."], ["Business", FiBriefcase, "Think bigger. Work smarter."], ["Health & fitness", FiActivity, "Invest in your everyday wellbeing."], ["Finance", FiDollarSign, "Make sense of the numbers."]];
export default function Landing() {
  return <div className="landing-page"><header className="public-header"><Brand /><nav aria-label="Main navigation"><a className="public-topic-link" href="#subjects">Explore subjects</a><Link className="public-signin" to="/login">Sign in</Link><Link className="btn btn-primary" to="/signup">Get started <FiArrowUpRight /></Link></nav></header>
    <main><section className="landing-hero"><div className="landing-hero-copy"><span className="eyebrow"><span className="status-dot" /> FOR THE CURIOUS. FOR THE AMBITIOUS.</span><h1>Learn something.<br /><em>Change everything.</em></h1><p>A new skill can open a whole new world. Discover courses that help you move forward, one good idea at a time.</p><div className="hero-buttons"><Link className="btn btn-primary" to="/signup">Find your next chapter <FiArrowRight /></Link><a className="btn btn-outline" href="#subjects">Explore subjects</a></div><div className="hero-reassurance"><span><FiCheck />At your own pace</span><span><FiCheck />Across seven subjects</span></div></div>
    <div className="hero-visual" aria-label="Illustration of your personal learning journey"><div className="visual-topline"><span>THE POSSIBILITIES ARE OPEN</span><FiArrowUpRight /></div><div className="visual-word">Stay<br /><em>curious.</em></div><div className="visual-orbit" aria-hidden="true"><FiBookOpen /></div><div className="visual-lesson"><span className="lesson-play"><FiPlay /></span><div><small>YOUR NEXT CHAPTER</small><strong>A skill worth starting.</strong><span>Explore · Learn · Grow</span></div><FiArrowRight /></div><div className="visual-bottom"><span>01 / A fresh perspective</span><span>learned.</span></div></div></section>
    <div className="landing-principles"><span>Big possibilities.<br /><strong>Small, everyday steps.</strong></span><p>Practical skills for real life</p><p>Learning that fits your schedule</p><p>A world of subjects to explore</p></div>
    <section id="subjects" className="landing-subjects"><div className="section-heading"><div><span className="eyebrow">FOLLOW YOUR CURIOSITY</span><h2>Where will you go next?</h2></div><p>Find a subject that speaks to you.</p></div><div className="landing-topic-grid">{topics.map(([title, Icon, description], index) => <Link className="landing-topic" to="/signup" key={title}><span className={`category-icon tone-${index % 4}`}><Icon /></span><div><h3>{title}</h3><p>{description}</p></div><FiArrowUpRight /></Link>)}</div></section>
    <section className="landing-how"><div><span className="eyebrow">PROGRESS, ON YOUR TERMS</span><h2>Make learning<br /><em>part of your life.</em></h2><Link className="btn btn-primary" to="/signup">Let’s get started <FiArrowRight /></Link></div><ol>{[["Find your spark", "Explore subjects, discover courses, and choose the skills you want to build."], ["Make it yours", "Save your favorites and keep your next steps together in your personal account."], ["Keep growing", "Come back to your learning and take the next step whenever you’re ready."]].map(([title, text], i) => <li key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section></main>
    <footer className="public-footer"><Brand /><p>Make curiosity a habit.</p><span>© {new Date().getFullYear()} Learned</span></footer></div>;
}
